### ISSUE TITLE
Error occurred in Python command: expected string or buffer

### ISSUE THREAD

**Issue by vitaliel** [tmm1/gdb.rb#2]
sudo /var/lib/gems/1.8/bin/gdb.rb 27012
(gdb) ruby trace 25
$1 = -61 '\303'
$2 = 0
$3 = 45991120
Breakpoint 1 at 0x14e1100
0x00002aaaaad05b3f in ?? () from /usr/lib/libruby1.8.so.1.8
$4 = 0
$5 = 0
$6 = 45991104
Traceback (most recent call last):
  File "/var/lib/gems/1.8/gems/gdb.rb-0.1.0/bin/../scripts/ruby-gdb.py", line 217, in invoke
    if not re.search('signaled while in a function called from GDB', text):
  File "/usr/lib/python2.5/re.py", line 142, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
Error occurred in Python command: expected string or buffer

**Comment by tmm1** [comment]
Missing debug symbols, see #1
