### ISSUE TITLE
Error occurred in Python command: No symbol "timeofday" in current context.

### ISSUE THREAD

**Issue by vitaliel** [tmm1/gdb.rb#3]
(gdb) ruby threads
Traceback (most recent call last):
  File "/var/lib/gems/1.8/gems/gdb.rb-0.1.0/bin/../scripts/ruby-gdb.py", line 31, in invoke
    self.show()
  File "/var/lib/gems/1.8/gems/gdb.rb-0.1.0/bin/../scripts/ruby-gdb.py", line 65, in show
    self.now = gdb.eval('timeofday()')
RuntimeError: No symbol "timeofday" in current context.
Error occurred in Python command: No symbol "timeofday" in current context.

**Comment by vitaliel** [comment]
I posted an article how to install gem on debian lenny: http://tech-blog.assembla.com/articles/2009/11/06/install-gdb-rb-on-debian-lenny/

**Comment by tmm1** [comment]
gdb.rb won't work with debian's ruby, since debian strips their binaries. I recommend installing REE instead.

**Comment by vitaliel** [comment]
you can install debug symbols with 

# apt-get install libruby1.8-dbg

I think timeofday() error is from python

**Comment by tmm1** [comment]
You can try libruby1.8-dbg, but gdb7 probably won't know to look for the debug symbols wherever debian puts them. The timeofday() error is because the binary is stripped.

**Comment by vitaliel** [comment]
I can try, is it a way to tell gdb.rb to look in /usr/lib/debug/usr/lib/ruby/1.8/x86_64-linux/ for debug symbols ?

**Comment by tmm1** [comment]
The gdb command is

```
set debug-file-directory /usr/lib/debug
```

but I need to figure out how to have gdb.rb set that before it loads in any of the ruby stuff. Can you try issuing that command right after gdb.rb starts up? It's probably too late by then.

**Comment by vitaliel** [comment]
I modified gdb.rb executable  and added -x /home/user/.gdb, but it still can not read symbols.

ok, thank you. it is too later here...

**Comment by tmm1** [comment]
I tried -x, but it doesn't autoload .gdbinit from the specified directory. If you modify your gdb.rb to call

```
gdb -ex 'set debug-file-directory /usr/lib/debug'
```

it should work.

**Comment by tmm1** [comment]
any luck?

**Comment by vitaliel** [comment]
Aman,  I run gdb.rb with this command and it does not load debug symbols.

cmd = "#{File.dirname(**FILE**)}/../ext/dst/bin/gdb -ex 'set debug-file-directory /usr/lib/debug' -ex 'py execfile(\"#{File.dirname(**FILE**)}/../scripts/ruby-gdb.py\")' #{ARGV.join(" ")}"
exec(cmd)

**Comment by tmm1** [comment]
what happens when you use debian's gdb to connect to that process and type `where` to get a backtrace.. does it have symbols or just '???'

**Comment by vitaliel** [comment]
Here is the output from gdb commands.
http://pastie.org/689445 - gdb 7 from debian sid
http://pastie.org/689448 - gdb.rb gem, it shows ?? for some symbols

**Comment by tmm1** [comment]
did gdb.rb show any lines like
    Reading symbols from /usr/bin/ruby1.8...Reading symbols from /usr/lib/debug/usr/bin/ruby1.8...done.
mentioning /usr/lib/debug ?

**Comment by vitaliel** [comment]
no, it only checks /usr/lib/ and /usr/bin

**Comment by tmm1** [comment]
This seems to work if you do gdb -ex 'set debug-file-directory /usr/lib/debug' -ex 'attach PID' /usr/bin/ruby1.8

I'll update the gem accordingly, some of the python script will need to change as well since it assumes REE

**Comment by tmm1** [comment]
I've pushed a new gem which fixes the /usr/lib/debug issue
