### ISSUE TITLE
Can't build with Python 2.7

### ISSUE THREAD

**Issue by nirvdrum** [tmm1/gdb.rb#7]
Ubuntu 11.04 ships with Python 2.7.  gdb.rb checks for 2.3, 2.4, or 2.5.  I have no idea whether 2.7 is compatible or not.  I hope to look in more when I get some time.

**Comment by tmm1** [comment]
This was fixed in 4323183ec262acac0a71622efe207d97379150fd, I need to push out a new gem.

**Comment by tmm1** [comment]
Pushed 0.1.7 to rubygems.

**Comment by nirvdrum** [comment]
Thanks.  I guess I should have looked through the history first.
